# Generated by Django 4.2.4 on 2023-08-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
